import { Button } from "@/components/ui/button"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { Zap, Target, BarChart } from "lucide-react"
import Link from "next/link"
import Navbar from "@/components/navbar"

export default function LandingPage() {
  return (
    <div className="min-h-screen bg-slate-50">
      <Navbar />

      {/* Hero Section */}
      <section className="px-4 py-20 text-center">
        <div className="max-w-4xl mx-auto">
          <h1 className="text-5xl md:text-6xl font-bold text-slate-800 mb-6">Your Personal AI Nutritionist</h1>
          <p className="text-xl text-slate-600 mb-8 max-w-2xl mx-auto">
            Generate custom meal plans and track your progress effortlessly with our AI-powered fitness and nutrition
            platform.
          </p>
          <Link href="/signup">
            <Button size="lg" className="bg-green-500 hover:bg-green-600 text-white px-8 py-4 text-lg">
              Get Started for Free
            </Button>
          </Link>
        </div>
      </section>

      {/* Features Section */}
      <section className="px-4 py-16 bg-white">
        <div className="max-w-6xl mx-auto">
          <h2 className="text-3xl font-bold text-center text-slate-800 mb-12">
            Everything you need to reach your goals
          </h2>
          <div className="grid md:grid-cols-3 gap-8">
            <Card className="text-center border-slate-200">
              <CardHeader>
                <div className="w-12 h-12 bg-green-100 rounded-lg flex items-center justify-center mx-auto mb-4">
                  <Zap className="w-6 h-6 text-green-600" />
                </div>
                <CardTitle className="text-slate-800">AI Meal Plans</CardTitle>
              </CardHeader>
              <CardContent>
                <CardDescription className="text-slate-600">
                  Get personalized meal plans generated by AI based on your goals, preferences, and dietary
                  restrictions.
                </CardDescription>
              </CardContent>
            </Card>

            <Card className="text-center border-slate-200">
              <CardHeader>
                <div className="w-12 h-12 bg-green-100 rounded-lg flex items-center justify-center mx-auto mb-4">
                  <Target className="w-6 h-6 text-green-600" />
                </div>
                <CardTitle className="text-slate-800">Track Your Progress</CardTitle>
              </CardHeader>
              <CardContent>
                <CardDescription className="text-slate-600">
                  Monitor your daily nutrition intake, water consumption, and weight progress with intuitive tracking
                  tools.
                </CardDescription>
              </CardContent>
            </Card>

            <Card className="text-center border-slate-200">
              <CardHeader>
                <div className="w-12 h-12 bg-green-100 rounded-lg flex items-center justify-center mx-auto mb-4">
                  <BarChart className="w-6 h-6 text-green-600" />
                </div>
                <CardTitle className="text-slate-800">Smart Analytics</CardTitle>
              </CardHeader>
              <CardContent>
                <CardDescription className="text-slate-600">
                  Visualize your progress with detailed charts and insights to stay motivated and on track.
                </CardDescription>
              </CardContent>
            </Card>
          </div>
        </div>
      </section>
    </div>
  )
}
